;this file for FamiTone2 library generated by text2data tool

nq_nespeccy_bug_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env4,@env0,@env0
	.byte $00
	.byte $f0 ;instrument $02
	.word @env2,@env17,@env0
	.byte $00
	.byte $f0 ;instrument $03
	.word @env3,@env17,@env0
	.byte $00
	.byte $f0 ;instrument $04
	.word @env2,@env18,@env0
	.byte $00
	.byte $f0 ;instrument $05
	.word @env3,@env18,@env0
	.byte $00
	.byte $f0 ;instrument $06
	.word @env2,@env19,@env0
	.byte $00
	.byte $f0 ;instrument $07
	.word @env3,@env19,@env0
	.byte $00
	.byte $f0 ;instrument $08
	.word @env2,@env20,@env0
	.byte $00
	.byte $f0 ;instrument $09
	.word @env3,@env20,@env0
	.byte $00
	.byte $30 ;instrument $0a
	.word @env1,@env16,@env0
	.byte $00
	.byte $30 ;instrument $0b
	.word @env1,@env21,@env0
	.byte $00
	.byte $30 ;instrument $0c
	.word @env5,@env22,@env0
	.byte $00
	.byte $30 ;instrument $0d
	.word @env6,@env23,@env0
	.byte $00
	.byte $30 ;instrument $0e
	.word @env7,@env24,@env0
	.byte $00
	.byte $30 ;instrument $0f
	.word @env8,@env25,@env0
	.byte $00
	.byte $30 ;instrument $10
	.word @env9,@env26,@env0
	.byte $00
	.byte $30 ;instrument $11
	.word @env10,@env27,@env0
	.byte $00
	.byte $30 ;instrument $12
	.word @env11,@env28,@env0
	.byte $00
	.byte $30 ;instrument $13
	.word @env12,@env29,@env0
	.byte $00
	.byte $30 ;instrument $14
	.word @env13,@env30,@env0
	.byte $00
	.byte $b0 ;instrument $15
	.word @env14,@env31,@env0
	.byte $00
	.byte $b0 ;instrument $16
	.word @env15,@env0,@env35
	.byte $00
	.byte $b0 ;instrument $17
	.word @env14,@env32,@env0
	.byte $00
	.byte $b0 ;instrument $18
	.word @env1,@env33,@env0
	.byte $00
	.byte $b0 ;instrument $19
	.word @env15,@env33,@env0
	.byte $00
	.byte $f0 ;instrument $1a
	.word @env3,@env34,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$00,$00
@env2:
	.byte $c0,$c1,$c1,$c2,$c2,$c3,$c3,$c4,$c4,$c5,$02,$c6,$c6,$c7,$c7,$c8
	.byte $c8,$c9,$c9,$ca,$ca,$cb,$cb,$00,$16
@env3:
	.byte $cd,$02,$cc,$03,$cb,$02,$ca,$03,$c9,$03,$c8,$02,$c7,$03,$c6,$03
	.byte $c5,$02,$c4,$03,$c3,$02,$c2,$03,$c1,$03,$c0,$00,$1a
@env4:
	.byte $c5,$00,$00
@env5:
	.byte $c9,$c5,$c3,$c0,$00,$03
@env6:
	.byte $c0,$c1,$c2,$c2,$c3,$c3,$c4,$c5,$c5,$c6,$c7,$c7,$c8,$c8,$c9,$ca
	.byte $ca,$cb,$cc,$cc,$cd,$cd,$ce,$cf,$cd,$cb,$c9,$c7,$c5,$c3,$c2,$c0
	.byte $00,$1f
@env7:
	.byte $cf,$04,$c0,$00,$02
@env8:
	.byte $c9,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$03,$c2,$03,$c1,$04
	.byte $c0,$00,$10
@env9:
	.byte $cf,$09,$c0,$00,$02
@env10:
	.byte $cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00
	.byte $0e
@env11:
	.byte $cf,$cf,$c0,$cf,$cf,$c0,$cf,$cf,$c0,$cf,$04,$c0,$00,$0b
@env12:
	.byte $cf,$cb,$c5,$cf,$cb,$c5,$cf,$cb,$c5,$cf,$cb,$c5,$c4,$c3,$c2,$c1
	.byte $00,$0f
@env13:
	.byte $c9,$c5,$c3,$03,$c2,$07,$c1,$08,$c0,$00,$08
@env14:
	.byte $cd,$ce,$00,$01
@env15:
	.byte $c4,$04,$c4,$00,$00
@env16:
	.byte $c0,$02,$bf,$04,$be,$03,$bd,$04,$bc,$03,$bb,$04,$ba,$03,$b9,$03
	.byte $b8,$04,$b7,$03,$b6,$b6,$b5,$b5,$b4,$00,$18
@env17:
	.byte $c0,$c0,$c3,$c3,$c7,$c7,$ca,$cc,$cf,$00,$00
@env18:
	.byte $c0,$c0,$c2,$c2,$c7,$c7,$ca,$cc,$ce,$00,$00
@env19:
	.byte $c0,$c0,$c2,$c2,$c5,$c5,$ca,$cc,$ce,$00,$00
@env20:
	.byte $c0,$c0,$c4,$c4,$c7,$c7,$c9,$cc,$c4,$00,$00
@env21:
	.byte $ab,$ac,$ad,$ad,$ae,$ae,$af,$02,$b0,$b0,$b1,$02,$b2,$b2,$b3,$b3
	.byte $b4,$02,$b5,$b5,$b6,$02,$b7,$b7,$b8,$b8,$b9,$02,$ba,$ba,$bb,$02
	.byte $bc,$bc,$bd,$bd,$be,$02,$bf,$bf,$c0,$00,$28
@env22:
	.byte $bc,$be,$bf,$c0,$00,$03
@env23:
	.byte $b5,$b5,$b6,$b6,$b7,$b7,$b8,$02,$b9,$b9,$ba,$ba,$bb,$bb,$bc,$bc
	.byte $bd,$bd,$be,$be,$bf,$bf,$c0,$00,$16
@env24:
	.byte $bc,$b8,$ae,$a9,$00,$03
@env25:
	.byte $c0,$09,$bf,$0b,$be,$0a,$bd,$0a,$bc,$02,$bc,$00,$0a
@env26:
	.byte $c0,$be,$bc,$ba,$b8,$b6,$b4,$b2,$b0,$00,$08
@env27:
	.byte $c6,$c3,$c0,$bd,$c0,$bd,$c0,$bd,$c0,$bd,$00,$09
@env28:
	.byte $c0,$bb,$b6,$c0,$bb,$b6,$c0,$bb,$b6,$c0,$bb,$b6,$b4,$b2,$b0,$00
	.byte $0e
@env29:
	.byte $c6,$c3,$c0,$c6,$c3,$c0,$c6,$c3,$c0,$bd,$c0,$bd,$c0,$bd,$c0,$bd
	.byte $00,$0f
@env30:
	.byte $bc,$be,$00,$01
@env31:
	.byte $be,$ca,$bf,$c0,$00,$03
@env32:
	.byte $c0,$cc,$c0,$c0,$00,$03
@env33:
	.byte $c0,$c1,$c0,$00,$02
@env34:
	.byte $c0,$c0,$c5,$c5,$c8,$c8,$ca,$cc,$c5,$00,$00
@env35:
	.byte $c1,$02,$c0,$c0,$c0,$00,$00


@song0ch0:
	.byte $fb,$03
@song0ch0loop:
@ref0:
	.byte $00,$bd
@ref1:
	.byte $bf
@ref2:
	.byte $00,$bd
@ref3:
	.byte $bf
@ref4:
	.byte $00,$bd
@ref5:
	.byte $bf
@ref6:
	.byte $00,$bd
@ref7:
	.byte $bf
@ref8:
	.byte $00,$bd
@ref9:
	.byte $bf
@ref10:
	.byte $00,$bd
@ref11:
	.byte $bf
@ref12:
	.byte $00,$bd
@ref13:
	.byte $bf
@ref14:
	.byte $aa,$64,$8d,$ac,$64,$85,$ae,$62,$89,$ac,$65,$aa,$5a,$85,$ac,$63
	.byte $80,$59,$ac,$5a,$85
@ref15:
	.byte $aa,$5a,$8d,$ac,$5a,$85,$ae,$58,$89,$ac,$5a,$89,$aa,$50,$85,$ac
	.byte $58,$85
@ref16:
	.byte $aa,$5e,$8d,$82,$58,$85,$ae,$62,$89,$82,$5f,$aa,$5a,$85,$82,$63
	.byte $80,$59,$82,$5a,$85
@ref17:
	.byte $aa,$5e,$8d,$ac,$58,$85,$ae,$5a,$89,$82,$5f,$80,$4d,$ae,$51,$80
	.byte $55,$4d,$ae,$55,$80,$58,$81
@ref18:
	.byte $aa,$5a,$89,$82,$55,$ae,$58,$85,$82,$5a,$85,$80,$54,$85,$58,$85
	.byte $82,$54,$85,$aa,$5a,$85
@ref19:
	.byte $83,$82,$59,$ae,$5e,$85,$82,$5b,$80,$5a,$85,$82,$5f,$aa,$58,$85
	.byte $80,$55,$ae,$51,$80,$47,$41,$ae,$47,$80,$50,$81
@ref20:
	.byte $aa,$58,$89,$ae,$55,$82,$58,$85,$ae,$5e,$89,$59,$82,$5e,$85,$aa
	.byte $62,$8d
@ref21:
	.byte $ae,$69,$80,$5f,$63,$ae,$59,$80,$5e,$54,$58,$50,$54,$4a,$50,$46
	.byte $4a,$50,$54,$50,$54,$58,$54,$58,$5e,$58,$5e,$60,$62,$85
@ref22:
	.byte $82,$62,$85,$80,$58,$5a,$83,$b0,$58,$85,$5a,$85,$82,$58,$85,$b0
	.byte $54,$85,$82,$5a,$85,$b0,$5a,$85
@ref23:
	.byte $82,$54,$85,$80,$62,$64,$83,$b0,$5a,$85,$58,$85,$82,$5a,$85,$80
	.byte $60,$62,$83,$b0,$58,$85,$54,$85
@ref24:
	.byte $82,$58,$85,$80,$54,$58,$83,$b0,$54,$85,$58,$85,$82,$54,$85,$b0
	.byte $5e,$85,$82,$58,$85,$b0,$62,$85
@ref25:
	.byte $82,$5e,$85,$80,$66,$68,$83,$b0,$62,$85,$58,$85,$80,$60,$62,$83
	.byte $b0,$58,$85,$54,$85,$58,$85
@ref26:
	.byte $82,$54,$85,$80,$56,$58,$83,$b0,$54,$85,$58,$85,$50,$85,$46,$85
	.byte $50,$85,$80,$5c,$5e,$83
@ref27:
	.byte $82,$50,$85,$b0,$58,$85,$82,$5e,$85,$b0,$62,$85,$82,$58,$85,$80
	.byte $56,$58,$83,$b0,$54,$85,$58,$85
@ref28:
	.byte $82,$54,$85,$80,$5c,$5e,$87,$b0,$4a,$85,$82,$5f,$80,$4e,$50,$83
	.byte $5c,$5e,$87,$b0,$4a,$85,$82,$5e,$81
@ref29:
	.byte $80,$52,$54,$83,$b0,$5e,$85,$80,$4b,$b0,$51,$80,$55,$4b,$51,$b0
	.byte $59,$80,$4b,$b0,$59,$80,$60,$62,$87,$82,$58,$81
@ref30:
	.byte $62,$85,$b0,$65,$82,$63,$b0,$65,$01,$63,$b2,$65,$80,$63,$b2,$63
	.byte $b0,$5b,$82,$63,$80,$58,$5a,$87,$82,$5a,$81
@ref31:
	.byte $b0,$5b,$ac,$5a,$a5,$54,$91
@ref32:
	.byte $00,$9d
@ref33:
	.byte $8f,$80,$54,$00,$54,$00,$58,$5a,$83
@ref34:
	.byte $b0,$65,$5b,$b2,$65,$b0,$5a,$85,$80,$55,$b2,$5b,$82,$55,$b2,$5b
	.byte $b0,$5b,$55,$80,$51,$52,$54,$51,$b0,$4d,$82,$50,$81
@ref35:
	.byte $b0,$4c,$00,$4d,$01,$50,$00,$51,$b2,$4d,$80,$54,$82,$50,$b0,$54
	.byte $00,$80,$5e,$82,$54,$b0,$5b,$82,$5f,$b0,$5f,$80,$58,$5a,$83,$b0
	.byte $55,$82,$5a,$81
@ref36:
	.byte $b0,$59,$63,$82,$59,$80,$5c,$5e,$83,$59,$b0,$51,$80,$59,$b0,$51
	.byte $59,$82,$51,$80,$54,$58,$83,$51,$b0,$4b,$80,$50,$81
@ref37:
	.byte $b0,$4b,$80,$51,$4b,$59,$b0,$51,$80,$59,$b0,$51,$80,$59,$5e,$58
	.byte $62,$5e,$68,$62,$6c,$68,$62,$68,$62,$5e,$62,$5e,$58,$5e
@ref38:
	.byte $54,$58,$87,$82,$59,$b0,$54,$85,$82,$59,$80,$56,$58,$87,$b0,$51
	.byte $82,$59,$b0,$59,$82,$51,$b0,$63,$b2,$58,$81
@ref39:
	.byte $80,$5c,$5e,$87,$b2,$63,$b0,$58,$85,$82,$5f,$80,$5c,$5e,$87,$b0
	.byte $59,$82,$5f,$80,$52,$54,$83,$b0,$59,$82,$54,$81
@ref40:
	.byte $80,$54,$58,$87,$82,$59,$b0,$54,$85,$82,$59,$80,$56,$58,$87,$b0
	.byte $51,$82,$59,$80,$48,$4a,$83,$b0,$55,$82,$4a,$81
@ref41:
	.byte $80,$4e,$50,$87,$82,$55,$80,$52,$54,$87,$82,$51,$80,$56,$58,$83
	.byte $b0,$55,$80,$59,$5e,$58,$62,$5e,$82,$58,$50,$5e,$58
	.byte $ff,$11
	.word @ref30
@ref43:
	.byte $b0,$5b,$01,$80,$5b,$01,$b0,$59,$82,$5b,$80,$59,$b2,$59,$80,$56
	.byte $58,$83,$b0,$51,$82,$59,$80,$4e,$50,$83,$4b,$b2,$50,$81
@ref44:
	.byte $83,$82,$4b,$b0,$63,$82,$4b,$80,$63,$01,$48,$4a,$83,$b0,$59,$82
	.byte $4b,$80,$59,$00,$85,$b2,$59,$80,$52,$54,$83
@ref45:
	.byte $b0,$59,$82,$55,$80,$59,$01,$4e,$50,$83,$b0,$63,$82,$51,$80,$60
	.byte $62,$83,$01,$82,$63,$80,$5c,$5e,$87,$b2,$62,$81
@ref46:
	.byte $82,$5e,$85,$b0,$5f,$01,$5f,$01,$80,$51,$b2,$5f,$b0,$59,$82,$51
	.byte $b0,$59,$82,$59,$01,$b2,$59,$80,$55,$82,$58,$81
@ref47:
	.byte $b0,$59,$82,$55,$b0,$59,$01,$80,$51,$b2,$59,$b0,$55,$82,$51,$80
	.byte $52,$54,$83,$01,$b2,$55,$80,$4e,$50,$83,$01,$82,$54,$81
@ref48:
	.byte $50,$85,$b0,$59,$01,$80,$59,$01,$55,$b2,$59,$80,$58,$82,$54,$80
	.byte $59,$01,$55,$82,$59,$80,$5e,$82,$54,$b0,$5f,$82,$54,$81
@ref49:
	.byte $80,$59,$b2,$5f,$80,$62,$82,$58,$b0,$63,$80,$5c,$5e,$83,$68,$82
	.byte $5e,$b0,$69,$80,$60,$62,$83,$6c,$68,$62,$5e,$68,$62,$82,$5e,$58
	.byte $62,$5e,$58,$80,$50
@ref50:
	.byte $52,$54,$87,$82,$55,$b0,$43,$4d,$51,$55,$4d,$b2,$51,$80,$5b,$b2
	.byte $55,$80,$56,$58,$83,$5b,$82,$58,$81
@ref51:
	.byte $80,$52,$54,$87,$82,$5b,$b0,$43,$4d,$51,$55,$80,$3d,$43,$4d,$51
	.byte $b0,$35,$3d,$43,$4c,$81
@ref52:
	.byte $80,$52,$54,$87,$82,$55,$b0,$43,$4d,$51,$55,$b2,$4d,$51,$80,$5b
	.byte $82,$55,$80,$56,$58,$83,$5b,$82,$58,$81
@ref53:
	.byte $80,$58,$5a,$87,$82,$5b,$b0,$43,$4d,$55,$5b,$80,$4d,$55,$5b,$65
	.byte $54,$42,$4c,$3c,$42,$34,$3c,$2a
@ref54:
	.byte $54,$58,$83,$82,$59,$b0,$4a,$85,$82,$59,$80,$4e,$50,$83,$82,$4b
	.byte $51,$b0,$4a,$85,$80,$4e,$50,$83,$b0,$4b,$82,$50,$81
@ref55:
	.byte $b0,$40,$85,$82,$4b,$b0,$50,$85,$b2,$41,$80,$48,$4a,$8b,$82,$50
	.byte $85,$80,$44,$46,$87,$82,$4a,$81
@ref56:
	.byte $80,$54,$58,$83,$82,$47,$b0,$4a,$85,$82,$59,$80,$4e,$50,$83,$82
	.byte $4b,$51,$b0,$4a,$85,$80,$56,$58,$83,$b0,$4b,$82,$58,$81
@ref57:
	.byte $80,$3e,$40,$83,$b0,$3d,$39,$80,$3a,$3c,$83,$b0,$39,$33,$80,$36
	.byte $38,$83,$33,$b0,$39,$80,$41,$b0,$47,$4b,$80,$50,$81
@ref58:
	.byte $82,$47,$4b,$80,$52,$54,$9b,$82,$52,$54,$83,$80,$43,$4d,$4e,$50
	.byte $54,$81
@ref59:
	.byte $82,$4e,$50,$55,$80,$5a,$9d,$82,$63,$00,$91
@ref60:
	.byte $fb,$21,$00,$bd
@ref61:
	.byte $bf
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref62:
	.byte $86,$3c,$95,$3c,$a5
@ref63:
	.byte $3c,$95,$3c,$95,$40,$8d
@ref64:
	.byte $3c,$95,$3c,$a5
	.byte $ff,$06
	.word @ref63
@ref66:
	.byte $92,$38,$95,$38,$a5
@ref67:
	.byte $38,$95,$38,$95,$8a,$3c,$8d
	.byte $ff,$04
	.word @ref62
	.byte $ff,$06
	.word @ref63
@ref70:
	.byte $3c,$95,$3c,$a5
	.byte $ff,$06
	.word @ref63
	.byte $ff,$04
	.word @ref66
	.byte $ff,$06
	.word @ref67
	.byte $ff,$04
	.word @ref66
	.byte $ff,$06
	.word @ref67
	.byte $ff,$04
	.word @ref62
@ref77:
	.byte $3c,$95,$3c,$a5
@ref78:
	.byte $8a,$3c,$95,$3c,$a5
@ref79:
	.byte $3c,$95,$3c,$95,$3c,$8d
@ref80:
	.byte $8e,$3c,$95,$3c,$a5
@ref81:
	.byte $3c,$95,$3c,$a5
	.byte $ff,$04
	.word @ref66
@ref83:
	.byte $38,$95,$38,$95,$90,$38,$8d
	.byte $ff,$04
	.word @ref62
@ref85:
	.byte $3c,$95,$3c,$a5
	.byte $ff,$04
	.word @ref78
	.byte $ff,$06
	.word @ref79
	.byte $ff,$04
	.word @ref80
@ref89:
	.byte $3c,$95,$3c,$a5
	.byte $ff,$04
	.word @ref66
	.byte $ff,$06
	.word @ref83
	.byte $ff,$04
	.word @ref62
@ref93:
	.byte $3d,$80,$3c,$b9
@ref94:
	.byte $3c,$9d
@ref95:
	.byte $42,$8d,$82,$3c,$42,$46,$4c,$50,$54,$5a,$62
	.byte $ff,$04
	.word @ref62
@ref97:
	.byte $3c,$95,$3c,$a5
	.byte $ff,$04
	.word @ref78
	.byte $ff,$06
	.word @ref79
	.byte $ff,$04
	.word @ref80
@ref101:
	.byte $3c,$95,$3c,$a5
	.byte $ff,$04
	.word @ref66
	.byte $ff,$06
	.word @ref83
	.byte $ff,$04
	.word @ref62
@ref105:
	.byte $3c,$95,$3c,$a5
	.byte $ff,$04
	.word @ref78
	.byte $ff,$06
	.word @ref79
	.byte $ff,$04
	.word @ref80
@ref109:
	.byte $3c,$95,$3c,$a5
	.byte $ff,$04
	.word @ref66
	.byte $ff,$06
	.word @ref83
@ref112:
	.byte $84,$3c,$8d,$86,$3c,$8d,$84,$3c,$89,$86,$3c,$89,$8a,$3c,$85
@ref113:
	.byte $84,$3c,$8d,$86,$3c,$8d,$84,$3c,$89,$86,$3c,$89,$40,$85
	.byte $ff,$0a
	.word @ref112
	.byte $ff,$0a
	.word @ref113
@ref116:
	.byte $90,$38,$8d,$92,$38,$8d,$90,$38,$89,$92,$38,$89,$b4,$36,$85
@ref117:
	.byte $90,$38,$8d,$92,$38,$8d,$90,$38,$89,$92,$38,$89,$8a,$3c,$85
	.byte $ff,$0a
	.word @ref116
	.byte $ff,$0a
	.word @ref117
@ref120:
	.byte $84,$3c,$85,$86,$3c,$9d,$82,$63,$00,$91
@ref121:
	.byte $bf
@ref122:
	.byte $00,$bd
@ref123:
	.byte $bf
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref124:
	.byte $9c,$41,$80,$1d,$01,$1c,$85,$2b,$9c,$41,$80,$35,$a0,$49,$80,$35
	.byte $25,$2b,$01,$2b,$21,$1c,$81
@ref125:
	.byte $9c,$41,$80,$1d,$01,$1d,$01,$2b,$9c,$41,$80,$35,$a0,$49,$80,$35
	.byte $25,$2b,$01,$2b,$21,$a4,$48,$81
	.byte $ff,$11
	.word @ref124
	.byte $ff,$11
	.word @ref125
@ref128:
	.byte $9c,$41,$80,$1b,$33,$00,$85,$33,$9c,$41,$80,$25,$a0,$49,$80,$25
	.byte $33,$00,$85,$25,$21,$28,$81
@ref129:
	.byte $9c,$41,$80,$1b,$33,$9c,$40,$85,$80,$33,$9c,$41,$80,$25,$a0,$48
	.byte $85,$80,$21,$28,$85,$25,$21,$a4,$48,$81
@ref130:
	.byte $9c,$41,$80,$1d,$01,$1d,$a0,$49,$80,$2b,$9c,$41,$80,$35,$9c,$41
	.byte $80,$35,$25,$2b,$a0,$49,$80,$2b,$21,$1c,$81
@ref131:
	.byte $9c,$41,$80,$1d,$01,$1d,$a0,$49,$80,$2b,$9c,$41,$80,$35,$9c,$41
	.byte $80,$35,$25,$2b,$a0,$49,$80,$2b,$21,$a4,$48,$81
	.byte $ff,$11
	.word @ref130
	.byte $ff,$11
	.word @ref131
@ref134:
	.byte $9c,$41,$80,$1b,$33,$01,$a0,$49,$80,$33,$9c,$41,$80,$25,$9c,$41
	.byte $80,$25,$33,$01,$a0,$49,$80,$25,$21,$28,$81
@ref135:
	.byte $9c,$41,$80,$1b,$33,$9c,$41,$a0,$49,$80,$33,$9c,$41,$80,$25,$a0
	.byte $48,$85,$80,$21,$29,$a0,$49,$80,$25,$21,$a4,$48,$81
	.byte $ff,$11
	.word @ref134
@ref137:
	.byte $9c,$41,$80,$1b,$32,$85,$9c,$41,$80,$33,$9c,$41,$80,$25,$a0,$48
	.byte $85,$96,$32,$91,$a0,$48,$81
@ref138:
	.byte $9c,$41,$80,$1d,$1d,$9c,$41,$a0,$49,$80,$2b,$9c,$41,$80,$35,$9c
	.byte $41,$80,$35,$25,$2b,$a0,$49,$80,$2b,$21,$1c,$81
	.byte $ff,$11
	.word @ref131
@ref140:
	.byte $9c,$41,$80,$1b,$33,$01,$a0,$49,$80,$25,$9c,$41,$80,$25,$9c,$41
	.byte $80,$2b,$25,$01,$a0,$49,$80,$2b,$25,$32,$81
@ref141:
	.byte $9c,$41,$80,$1b,$33,$a4,$49,$a0,$49,$80,$25,$9c,$41,$80,$25,$a0
	.byte $49,$80,$2b,$25,$9c,$41,$a0,$49,$80,$2b,$9c,$41,$80,$32,$81
@ref142:
	.byte $9c,$41,$80,$29,$2f,$29,$a0,$49,$80,$39,$9c,$41,$80,$2f,$9c,$41
	.byte $80,$2f,$39,$41,$a0,$49,$80,$2f,$29,$00,$81
@ref143:
	.byte $9c,$41,$80,$29,$9c,$41,$80,$29,$a0,$49,$80,$39,$9c,$41,$80,$2f
	.byte $9c,$41,$80,$2f,$29,$a4,$49,$a0,$49,$80,$39,$2f,$a0,$48,$81
	.byte $ff,$11
	.word @ref134
@ref145:
	.byte $9c,$41,$80,$1b,$33,$9c,$41,$a0,$49,$80,$33,$9c,$41,$80,$25,$9c
	.byte $40,$85,$a0,$49,$96,$2a,$91
	.byte $ff,$11
	.word @ref130
	.byte $ff,$11
	.word @ref131
	.byte $ff,$11
	.word @ref140
	.byte $ff,$11
	.word @ref141
	.byte $ff,$11
	.word @ref142
	.byte $ff,$11
	.word @ref143
	.byte $ff,$11
	.word @ref134
@ref153:
	.byte $9c,$41,$80,$1b,$33,$9c,$41,$a0,$49,$80,$33,$9c,$41,$80,$25,$a0
	.byte $49,$49,$80,$21,$a4,$49,$a0,$49,$80,$25,$94,$20,$85
	.byte $ff,$11
	.word @ref130
@ref155:
	.byte $9c,$41,$80,$4c,$a5,$4a,$91
@ref156:
	.byte $48,$8d,$24,$8d
@ref157:
	.byte $96,$2a,$9d
	.byte $ff,$11
	.word @ref130
	.byte $ff,$11
	.word @ref131
	.byte $ff,$11
	.word @ref140
	.byte $ff,$11
	.word @ref141
	.byte $ff,$11
	.word @ref142
	.byte $ff,$11
	.word @ref143
	.byte $ff,$11
	.word @ref134
	.byte $ff,$0d
	.word @ref145
	.byte $ff,$11
	.word @ref138
	.byte $ff,$11
	.word @ref131
	.byte $ff,$11
	.word @ref140
	.byte $ff,$11
	.word @ref141
	.byte $ff,$11
	.word @ref142
	.byte $ff,$11
	.word @ref143
	.byte $ff,$11
	.word @ref134
	.byte $ff,$10
	.word @ref153
	.byte $ff,$11
	.word @ref138
	.byte $ff,$11
	.word @ref131
	.byte $ff,$11
	.word @ref130
	.byte $ff,$11
	.word @ref131
	.byte $ff,$11
	.word @ref134
	.byte $ff,$11
	.word @ref135
	.byte $ff,$11
	.word @ref134
@ref181:
	.byte $9c,$41,$80,$1b,$33,$9c,$41,$41,$80,$33,$9c,$41,$80,$25,$9c,$40
	.byte $85,$a0,$49,$80,$25,$21,$a4,$49,$a0,$49,$80,$24,$81
@ref182:
	.byte $9c,$41,$80,$1d,$01,$1d,$9c,$41,$80,$1d,$00,$a5
@ref183:
	.byte $bf
@ref184:
	.byte $00,$bd
@ref185:
	.byte $bf
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref186:
	.byte $9e,$18,$85,$98,$1d,$20,$89,$a8,$1c,$85,$a2,$12,$85,$98,$03,$1c
	.byte $89,$1d,$20,$81
@ref187:
	.byte $9e,$18,$85,$98,$1d,$21,$00,$85,$a8,$1c,$85,$a2,$14,$85,$98,$03
	.byte $1c,$89,$1d,$a6,$12,$81
	.byte $ff,$0f
	.word @ref186
	.byte $ff,$10
	.word @ref187
@ref190:
	.byte $9e,$18,$85,$98,$1d,$20,$89,$a8,$1c,$85,$a2,$14,$85,$98,$03,$1c
	.byte $89,$1d,$20,$81
@ref191:
	.byte $9e,$18,$85,$98,$1d,$20,$89,$a8,$1c,$85,$a2,$14,$85,$98,$03,$1c
	.byte $89,$1d,$a6,$12,$81
@ref192:
	.byte $9e,$18,$85,$98,$1d,$21,$a2,$12,$85,$a8,$1c,$85,$98,$1d,$21,$03
	.byte $1d,$a2,$14,$85,$98,$1d,$20,$81
@ref193:
	.byte $9e,$18,$85,$98,$1d,$21,$a2,$12,$85,$a8,$1c,$85,$98,$1d,$21,$03
	.byte $1d,$a2,$14,$85,$98,$1d,$a6,$12,$81
	.byte $ff,$11
	.word @ref192
	.byte $ff,$11
	.word @ref193
	.byte $ff,$11
	.word @ref192
@ref197:
	.byte $9e,$18,$85,$98,$1d,$21,$a2,$12,$85,$a8,$1c,$85,$a2,$14,$85,$98
	.byte $03,$1d,$a2,$14,$85,$98,$1d,$a6,$12,$81
	.byte $ff,$11
	.word @ref192
@ref199:
	.byte $9e,$18,$85,$98,$1d,$21,$9e,$18,$85,$a8,$1c,$85,$a2,$14,$85,$98
	.byte $03,$1c,$85,$9a,$1e,$85,$a2,$14,$81
	.byte $ff,$11
	.word @ref192
	.byte $ff,$11
	.word @ref193
	.byte $ff,$11
	.word @ref192
@ref203:
	.byte $9e,$18,$85,$98,$1d,$a6,$13,$a2,$12,$85,$a8,$1c,$85,$a2,$12,$85
	.byte $98,$03,$1d,$a2,$14,$85,$a8,$1d,$98,$20,$81
	.byte $ff,$11
	.word @ref192
@ref205:
	.byte $9e,$18,$85,$a8,$1d,$98,$21,$a2,$12,$85,$a8,$1c,$85,$98,$1d,$21
	.byte $03,$a6,$13,$a2,$14,$85,$98,$1d,$a2,$12,$81
	.byte $ff,$11
	.word @ref192
@ref207:
	.byte $9e,$18,$85,$98,$1d,$21,$a2,$12,$85,$a8,$1c,$85,$9e,$18,$85,$a2
	.byte $14,$85,$9a,$1e,$8d
	.byte $ff,$11
	.word @ref192
	.byte $ff,$11
	.word @ref193
	.byte $ff,$11
	.word @ref192
	.byte $ff,$11
	.word @ref203
	.byte $ff,$11
	.word @ref192
	.byte $ff,$11
	.word @ref205
	.byte $ff,$11
	.word @ref192
@ref215:
	.byte $9e,$18,$85,$98,$1d,$21,$a2,$12,$85,$a8,$1c,$85,$a2,$15,$15,$98
	.byte $03,$a6,$13,$a2,$14,$8d
	.byte $ff,$11
	.word @ref192
@ref217:
	.byte $9e,$19,$80,$1a,$a5,$16,$91
@ref218:
	.byte $12,$8d,$20,$8d
@ref219:
	.byte $02,$8d,$04,$06,$08,$0a,$9a,$1e,$85
	.byte $ff,$11
	.word @ref192
	.byte $ff,$11
	.word @ref193
	.byte $ff,$11
	.word @ref192
	.byte $ff,$11
	.word @ref203
	.byte $ff,$11
	.word @ref192
	.byte $ff,$11
	.word @ref205
	.byte $ff,$11
	.word @ref192
	.byte $ff,$0e
	.word @ref207
	.byte $ff,$11
	.word @ref192
	.byte $ff,$11
	.word @ref193
	.byte $ff,$11
	.word @ref192
	.byte $ff,$11
	.word @ref203
	.byte $ff,$11
	.word @ref192
	.byte $ff,$11
	.word @ref205
	.byte $ff,$11
	.word @ref192
	.byte $ff,$0e
	.word @ref215
	.byte $ff,$11
	.word @ref192
	.byte $ff,$11
	.word @ref193
	.byte $ff,$11
	.word @ref192
	.byte $ff,$11
	.word @ref193
	.byte $ff,$11
	.word @ref192
	.byte $ff,$11
	.word @ref197
	.byte $ff,$11
	.word @ref192
@ref243:
	.byte $9e,$18,$85,$98,$1d,$21,$9e,$18,$85,$98,$1d,$21,$9e,$18,$85,$a2
	.byte $14,$85,$98,$1d,$a6,$13,$a2,$14,$85
@ref244:
	.byte $9e,$18,$85,$98,$1d,$21,$9e,$18,$95,$80,$14,$0f,$20,$00,$8d
@ref245:
	.byte $a7,$14,$0f,$20,$00,$8d
@ref246:
	.byte $00,$bd
@ref247:
	.byte $bf
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref248:
	.byte $bf
@ref249:
	.byte $bf
@ref250:
	.byte $bf
@ref251:
	.byte $bf
@ref252:
	.byte $bf
@ref253:
	.byte $bf
@ref254:
	.byte $bf
@ref255:
	.byte $bf
@ref256:
	.byte $bf
@ref257:
	.byte $bf
@ref258:
	.byte $bf
@ref259:
	.byte $bf
@ref260:
	.byte $bf
@ref261:
	.byte $bf
@ref262:
	.byte $bf
@ref263:
	.byte $bf
@ref264:
	.byte $bf
@ref265:
	.byte $bf
@ref266:
	.byte $bf
@ref267:
	.byte $bf
@ref268:
	.byte $bf
@ref269:
	.byte $bf
@ref270:
	.byte $bf
@ref271:
	.byte $bf
@ref272:
	.byte $bf
@ref273:
	.byte $bf
@ref274:
	.byte $bf
@ref275:
	.byte $bf
@ref276:
	.byte $bf
@ref277:
	.byte $bf
@ref278:
	.byte $bf
@ref279:
	.byte $bf
@ref280:
	.byte $9f
@ref281:
	.byte $9f
@ref282:
	.byte $bf
@ref283:
	.byte $bf
@ref284:
	.byte $bf
@ref285:
	.byte $bf
@ref286:
	.byte $bf
@ref287:
	.byte $bf
@ref288:
	.byte $bf
@ref289:
	.byte $bf
@ref290:
	.byte $bf
@ref291:
	.byte $bf
@ref292:
	.byte $bf
@ref293:
	.byte $bf
@ref294:
	.byte $bf
@ref295:
	.byte $bf
@ref296:
	.byte $bf
@ref297:
	.byte $bf
@ref298:
	.byte $bf
@ref299:
	.byte $bf
@ref300:
	.byte $bf
@ref301:
	.byte $bf
@ref302:
	.byte $bf
@ref303:
	.byte $bf
@ref304:
	.byte $bf
@ref305:
	.byte $bf
@ref306:
	.byte $bf
@ref307:
	.byte $bf
@ref308:
	.byte $bf
@ref309:
	.byte $bf
	.byte $fd
	.word @song0ch4loop
