;this file for FamiTone2 library generated by text2data tool

nq_nespeccyb_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env4,@env0,@env0
	.byte $00
	.byte $f0 ;instrument $02
	.word @env2,@env17,@env0
	.byte $00
	.byte $f0 ;instrument $03
	.word @env3,@env17,@env0
	.byte $00
	.byte $f0 ;instrument $04
	.word @env2,@env18,@env0
	.byte $00
	.byte $f0 ;instrument $05
	.word @env3,@env18,@env0
	.byte $00
	.byte $f0 ;instrument $06
	.word @env2,@env19,@env0
	.byte $00
	.byte $f0 ;instrument $07
	.word @env3,@env19,@env0
	.byte $00
	.byte $f0 ;instrument $08
	.word @env2,@env20,@env0
	.byte $00
	.byte $f0 ;instrument $09
	.word @env3,@env20,@env0
	.byte $00
	.byte $30 ;instrument $0a
	.word @env1,@env16,@env0
	.byte $00
	.byte $30 ;instrument $0b
	.word @env1,@env21,@env0
	.byte $00
	.byte $30 ;instrument $0c
	.word @env5,@env22,@env0
	.byte $00
	.byte $30 ;instrument $0d
	.word @env6,@env23,@env0
	.byte $00
	.byte $30 ;instrument $0e
	.word @env7,@env24,@env0
	.byte $00
	.byte $30 ;instrument $0f
	.word @env8,@env25,@env0
	.byte $00
	.byte $30 ;instrument $10
	.word @env9,@env26,@env0
	.byte $00
	.byte $30 ;instrument $11
	.word @env10,@env27,@env0
	.byte $00
	.byte $30 ;instrument $12
	.word @env11,@env28,@env0
	.byte $00
	.byte $30 ;instrument $13
	.word @env12,@env29,@env0
	.byte $00
	.byte $30 ;instrument $14
	.word @env13,@env30,@env0
	.byte $00
	.byte $b0 ;instrument $15
	.word @env14,@env31,@env0
	.byte $00
	.byte $b0 ;instrument $16
	.word @env15,@env0,@env35
	.byte $00
	.byte $b0 ;instrument $17
	.word @env14,@env32,@env0
	.byte $00
	.byte $b0 ;instrument $18
	.word @env1,@env33,@env0
	.byte $00
	.byte $b0 ;instrument $19
	.word @env15,@env33,@env0
	.byte $00
	.byte $f0 ;instrument $1a
	.word @env3,@env34,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$00,$00
@env2:
	.byte $c0,$c1,$c1,$c2,$c2,$c3,$c3,$c4,$c4,$c5,$02,$c6,$c6,$c7,$c7,$c8
	.byte $c8,$c9,$c9,$ca,$ca,$cb,$cb,$00,$16
@env3:
	.byte $cd,$02,$cc,$03,$cb,$02,$ca,$03,$c9,$03,$c8,$02,$c7,$03,$c6,$03
	.byte $c5,$02,$c4,$03,$c3,$02,$c2,$03,$c1,$03,$c0,$00,$1a
@env4:
	.byte $c5,$00,$00
@env5:
	.byte $c9,$c5,$c3,$c0,$00,$03
@env6:
	.byte $c0,$c1,$c2,$c2,$c3,$c3,$c4,$c5,$c5,$c6,$c7,$c7,$c8,$c8,$c9,$ca
	.byte $ca,$cb,$cc,$cc,$cd,$cd,$ce,$cf,$cd,$cb,$c9,$c7,$c5,$c3,$c2,$c0
	.byte $00,$1f
@env7:
	.byte $cf,$04,$c0,$00,$02
@env8:
	.byte $c9,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$03,$c2,$03,$c1,$04
	.byte $c0,$00,$10
@env9:
	.byte $cf,$09,$c0,$00,$02
@env10:
	.byte $cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00
	.byte $0e
@env11:
	.byte $cf,$cf,$c0,$cf,$cf,$c0,$cf,$cf,$c0,$cf,$04,$c0,$00,$0b
@env12:
	.byte $cf,$cb,$c5,$cf,$cb,$c5,$cf,$cb,$c5,$cf,$cb,$c5,$c4,$c3,$c2,$c1
	.byte $00,$0f
@env13:
	.byte $c9,$c5,$c3,$03,$c2,$07,$c1,$08,$c0,$00,$08
@env14:
	.byte $cd,$ce,$00,$01
@env15:
	.byte $c4,$04,$c4,$00,$00
@env16:
	.byte $c0,$02,$bf,$04,$be,$03,$bd,$04,$bc,$03,$bb,$04,$ba,$03,$b9,$03
	.byte $b8,$04,$b7,$03,$b6,$b6,$b5,$b5,$b4,$00,$18
@env17:
	.byte $c0,$c0,$c3,$c3,$c7,$c7,$ca,$cc,$cf,$00,$00
@env18:
	.byte $c0,$c0,$c2,$c2,$c7,$c7,$ca,$cc,$ce,$00,$00
@env19:
	.byte $c0,$c0,$c2,$c2,$c5,$c5,$ca,$cc,$ce,$00,$00
@env20:
	.byte $c0,$c0,$c4,$c4,$c7,$c7,$c9,$cc,$c4,$00,$00
@env21:
	.byte $ab,$ac,$ad,$ad,$ae,$ae,$af,$02,$b0,$b0,$b1,$02,$b2,$b2,$b3,$b3
	.byte $b4,$02,$b5,$b5,$b6,$02,$b7,$b7,$b8,$b8,$b9,$02,$ba,$ba,$bb,$02
	.byte $bc,$bc,$bd,$bd,$be,$02,$bf,$bf,$c0,$00,$28
@env22:
	.byte $bc,$be,$bf,$c0,$00,$03
@env23:
	.byte $b5,$b5,$b6,$b6,$b7,$b7,$b8,$02,$b9,$b9,$ba,$ba,$bb,$bb,$bc,$bc
	.byte $bd,$bd,$be,$be,$bf,$bf,$c0,$00,$16
@env24:
	.byte $bc,$b8,$ae,$a9,$00,$03
@env25:
	.byte $c0,$09,$bf,$0b,$be,$0a,$bd,$0a,$bc,$02,$bc,$00,$0a
@env26:
	.byte $c0,$be,$bc,$ba,$b8,$b6,$b4,$b2,$b0,$00,$08
@env27:
	.byte $c6,$c3,$c0,$bd,$c0,$bd,$c0,$bd,$c0,$bd,$00,$09
@env28:
	.byte $c0,$bb,$b6,$c0,$bb,$b6,$c0,$bb,$b6,$c0,$bb,$b6,$b4,$b2,$b0,$00
	.byte $0e
@env29:
	.byte $c6,$c3,$c0,$c6,$c3,$c0,$c6,$c3,$c0,$bd,$c0,$bd,$c0,$bd,$c0,$bd
	.byte $00,$0f
@env30:
	.byte $bc,$be,$00,$01
@env31:
	.byte $be,$ca,$bf,$c0,$00,$03
@env32:
	.byte $c0,$cc,$c0,$c0,$00,$03
@env33:
	.byte $c0,$c1,$c0,$00,$02
@env34:
	.byte $c0,$c0,$c2,$c2,$c4,$c4,$c7,$cc,$c4,$00,$00
@env35:
	.byte $c1,$02,$c0,$c0,$c0,$00,$00


@song0ch0:
	.byte $fb,$03
@song0ch0loop:
@ref0:
	.byte $fb,$03,$82,$62,$85,$b0,$65,$82,$63,$b0,$65,$01,$63,$b2,$65,$80
	.byte $63,$b2,$63,$b0,$5b,$82,$63,$80,$58,$5a,$87,$82,$5b,$b0,$5b,$ac
	.byte $5a,$a5,$54,$91
@ref1:
	.byte $00,$ad,$80,$54,$00,$54,$00,$58,$5a,$83
@ref2:
	.byte $b0,$65,$5b,$b2,$65,$b0,$5a,$85,$80,$55,$b2,$5b,$82,$55,$b2,$5b
	.byte $b0,$5b,$55,$80,$51,$52,$54,$51,$b0,$4d,$82,$51,$b0,$4c,$00,$4d
	.byte $01,$50,$00,$51,$b2,$4d,$80,$54,$82,$50,$b0,$54,$00,$80,$5e,$82
	.byte $54,$b0,$5b,$82,$5f,$b0,$5f,$80,$58,$5a,$83,$b0,$55,$82,$5a,$81
@ref3:
	.byte $b0,$59,$63,$82,$59,$80,$5c,$5e,$83,$59,$b0,$51,$80,$59,$b0,$51
	.byte $59,$82,$51,$80,$54,$58,$83,$51,$b0,$4b,$80,$51,$b0,$4b,$80,$51
	.byte $4b,$59,$b0,$51,$80,$59,$b0,$51,$80,$59,$5e,$58,$62,$5e,$68,$62
	.byte $6c,$68,$62,$68,$62,$5e,$62,$5e,$58,$5e
@ref4:
	.byte $54,$58,$87,$82,$59,$b0,$54,$85,$82,$59,$80,$56,$58,$87,$b0,$51
	.byte $82,$59,$b0,$59,$82,$51,$b0,$63,$b2,$59,$80,$5c,$5e,$87,$b2,$63
	.byte $b0,$58,$85,$82,$5f,$80,$5c,$5e,$87,$b0,$59,$82,$5f,$80,$52,$54
	.byte $83,$b0,$59,$82,$54,$81
@ref5:
	.byte $80,$54,$58,$87,$82,$59,$b0,$54,$85,$82,$59,$80,$56,$58,$87,$b0
	.byte $51,$82,$59,$80,$48,$4a,$83,$b0,$55,$82,$4b,$80,$4e,$50,$87,$82
	.byte $55,$80,$52,$54,$87,$82,$51,$80,$56,$58,$83,$b0,$55,$80,$59,$5e
	.byte $58,$62,$5e,$58,$50,$5e,$58
@ref6:
	.byte $82,$62,$85,$b0,$65,$82,$63,$b0,$65,$01,$63,$b2,$65,$80,$63,$b2
	.byte $63,$b0,$5b,$82,$63,$80,$58,$5a,$87,$82,$5b,$b0,$5b,$01,$80,$5b
	.byte $01,$b0,$59,$82,$5b,$80,$59,$b2,$59,$80,$56,$58,$83,$b0,$51,$82
	.byte $59,$80,$4e,$50,$83,$4b,$b2,$50,$81
@ref7:
	.byte $83,$82,$4b,$b0,$63,$82,$4b,$80,$63,$01,$48,$4a,$83,$b0,$59,$82
	.byte $4b,$80,$59,$00,$85,$b2,$59,$80,$52,$54,$83,$b0,$59,$82,$55,$80
	.byte $59,$01,$4e,$50,$83,$b0,$63,$82,$51,$80,$60,$62,$83,$01,$82,$63
	.byte $80,$5c,$5e,$87,$b2,$62,$81
@ref8:
	.byte $82,$5e,$85,$b0,$5f,$01,$5f,$01,$80,$51,$b2,$5f,$b0,$59,$82,$51
	.byte $b0,$59,$82,$59,$01,$b2,$59,$80,$55,$01,$b0,$59,$82,$55,$b0,$59
	.byte $01,$80,$51,$b2,$59,$b0,$55,$82,$51,$80,$52,$54,$83,$01,$b2,$55
	.byte $80,$4e,$50,$83,$01,$82,$54,$81
@ref9:
	.byte $50,$85,$b0,$59,$01,$80,$59,$01,$55,$b2,$59,$80,$58,$82,$54,$80
	.byte $59,$01,$55,$82,$59,$80,$5e,$82,$54,$b0,$5f,$82,$55,$80,$59,$b2
	.byte $5f,$80,$62,$82,$58,$b0,$63,$80,$5c,$5e,$83,$68,$82,$5e,$b0,$69
	.byte $80,$60,$62,$83,$6c,$68,$62,$5e,$68,$62,$5e,$58,$62,$5e,$58,$50
@ref10:
	.byte $00,$f9,$83
@ref11:
	.byte $00,$f9,$83
@ref12:
	.byte $f9,$85
@ref13:
	.byte $f9,$85
@ref14:
	.byte $00,$f9,$83
@ref15:
	.byte $00,$f9,$83
@ref16:
	.byte $f9,$85
@ref17:
	.byte $f9,$85
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref18:
	.byte $86,$3c,$95,$3c,$a5,$3d,$80,$3c,$b9
@ref19:
	.byte $3c,$9d,$42,$8d,$82,$3c,$42,$46,$4c,$50,$54,$5a,$62
@ref20:
	.byte $86,$3c,$95,$3c,$a5,$3c,$95,$3c,$a5
@ref21:
	.byte $8a,$3c,$95,$3c,$a5,$3c,$95,$3c,$95,$3c,$8d
@ref22:
	.byte $8e,$3c,$95,$3c,$a5,$3c,$95,$3c,$a5
@ref23:
	.byte $92,$38,$95,$38,$a5,$38,$95,$38,$95,$38,$8d
	.byte $ff,$08
	.word @ref20
	.byte $ff,$0a
	.word @ref21
	.byte $ff,$08
	.word @ref22
	.byte $ff,$0a
	.word @ref23
@ref28:
	.byte $84,$3c,$8d,$86,$3c,$8d,$84,$3c,$89,$86,$3c,$89,$8a,$3c,$85,$84
	.byte $3c,$8d,$86,$3c,$8d,$84,$3c,$89,$86,$3c,$89,$40,$85
	.byte $ff,$14
	.word @ref28
@ref30:
	.byte $90,$38,$8d,$92,$38,$8d,$90,$38,$89,$92,$38,$89,$b4,$36,$85,$90
	.byte $38,$8d,$92,$38,$8d,$90,$38,$89,$92,$38,$89,$8a,$3c,$85
	.byte $ff,$14
	.word @ref30
	.byte $ff,$14
	.word @ref28
	.byte $ff,$14
	.word @ref28
	.byte $ff,$14
	.word @ref30
	.byte $ff,$14
	.word @ref30
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref36:
	.byte $9c,$41,$80,$1d,$01,$1d,$a0,$49,$80,$2b,$9c,$41,$80,$35,$9c,$41
	.byte $80,$35,$25,$2b,$a0,$49,$80,$2b,$21,$1d,$9c,$41,$80,$4c,$a5,$4a
	.byte $91
@ref37:
	.byte $48,$8d,$24,$8d,$96,$2a,$9d
@ref38:
	.byte $9c,$41,$80,$1d,$01,$1d,$a0,$49,$80,$2b,$9c,$41,$80,$35,$9c,$41
	.byte $80,$35,$25,$2b,$a0,$49,$80,$2b,$21,$1d,$9c,$41,$80,$1d,$01,$1d
	.byte $a0,$49,$80,$2b,$9c,$41,$80,$35,$9c,$41,$80,$35,$25,$2b,$a0,$49
	.byte $80,$2b,$21,$a4,$48,$81
@ref39:
	.byte $9c,$41,$80,$1b,$33,$01,$a0,$49,$80,$25,$9c,$41,$80,$25,$9c,$41
	.byte $80,$2b,$25,$01,$a0,$49,$80,$2b,$25,$33,$9c,$41,$80,$1b,$33,$a4
	.byte $49,$a0,$49,$80,$25,$9c,$41,$80,$25,$a0,$49,$80,$2b,$25,$9c,$41
	.byte $a0,$49,$80,$2b,$9c,$41,$80,$32,$81
@ref40:
	.byte $9c,$41,$80,$29,$2f,$29,$a0,$49,$80,$39,$9c,$41,$80,$2f,$9c,$41
	.byte $80,$2f,$39,$41,$a0,$49,$80,$2f,$29,$01,$9c,$41,$80,$29,$9c,$41
	.byte $80,$29,$a0,$49,$80,$39,$9c,$41,$80,$2f,$9c,$41,$80,$2f,$29,$a4
	.byte $49,$a0,$49,$80,$39,$2f,$a0,$48,$81
@ref41:
	.byte $9c,$41,$80,$1b,$33,$01,$a0,$49,$80,$33,$9c,$41,$80,$25,$9c,$41
	.byte $80,$25,$33,$01,$a0,$49,$80,$25,$21,$29,$9c,$41,$80,$1b,$33,$9c
	.byte $41,$a0,$49,$80,$33,$9c,$41,$80,$25,$a0,$48,$85,$80,$21,$29,$a0
	.byte $49,$80,$25,$21,$a4,$48,$81
	.byte $ff,$21
	.word @ref38
	.byte $ff,$21
	.word @ref39
	.byte $ff,$21
	.word @ref40
	.byte $ff,$21
	.word @ref41
	.byte $ff,$21
	.word @ref38
	.byte $ff,$21
	.word @ref38
	.byte $ff,$21
	.word @ref41
	.byte $ff,$21
	.word @ref41
	.byte $ff,$21
	.word @ref38
	.byte $ff,$21
	.word @ref38
	.byte $ff,$21
	.word @ref41
	.byte $ff,$21
	.word @ref41
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref54:
	.byte $9e,$18,$85,$98,$1d,$21,$a2,$12,$85,$a8,$1c,$85,$98,$1d,$21,$03
	.byte $1d,$a2,$14,$85,$98,$1d,$21,$9e,$19,$80,$1a,$a5,$16,$91
@ref55:
	.byte $12,$8d,$20,$8d,$02,$8d,$04,$06,$08,$0a,$9a,$1e,$85
@ref56:
	.byte $9e,$18,$85,$98,$1d,$21,$a2,$12,$85,$a8,$1c,$85,$98,$1d,$21,$03
	.byte $1d,$a2,$14,$85,$98,$1d,$21,$9e,$18,$85,$98,$1d,$21,$a2,$12,$85
	.byte $a8,$1c,$85,$98,$1d,$21,$03,$1d,$a2,$14,$85,$98,$1d,$a6,$12,$81
@ref57:
	.byte $9e,$18,$85,$98,$1d,$21,$a2,$12,$85,$a8,$1c,$85,$98,$1d,$21,$03
	.byte $1d,$a2,$14,$85,$98,$1d,$21,$9e,$18,$85,$98,$1d,$a6,$13,$a2,$12
	.byte $85,$a8,$1c,$85,$a2,$12,$85,$98,$03,$1d,$a2,$14,$85,$a8,$1d,$98
	.byte $20,$81
@ref58:
	.byte $9e,$18,$85,$98,$1d,$21,$a2,$12,$85,$a8,$1c,$85,$98,$1d,$21,$03
	.byte $1d,$a2,$14,$85,$98,$1d,$21,$9e,$18,$85,$a8,$1d,$98,$21,$a2,$12
	.byte $85,$a8,$1c,$85,$98,$1d,$21,$03,$a6,$13,$a2,$14,$85,$98,$1d,$a2
	.byte $12,$81
@ref59:
	.byte $9e,$18,$85,$98,$1d,$21,$a2,$12,$85,$a8,$1c,$85,$98,$1d,$21,$03
	.byte $1d,$a2,$14,$85,$98,$1d,$21,$9e,$18,$85,$98,$1d,$21,$a2,$12,$85
	.byte $a8,$1c,$85,$a2,$14,$85,$98,$03,$1d,$a2,$14,$85,$98,$1d,$a6,$12
	.byte $81
	.byte $ff,$21
	.word @ref56
	.byte $ff,$21
	.word @ref57
	.byte $ff,$21
	.word @ref58
	.byte $ff,$21
	.word @ref59
	.byte $ff,$21
	.word @ref56
	.byte $ff,$21
	.word @ref56
	.byte $ff,$21
	.word @ref59
	.byte $ff,$21
	.word @ref59
	.byte $ff,$21
	.word @ref56
	.byte $ff,$21
	.word @ref56
	.byte $ff,$21
	.word @ref59
	.byte $ff,$21
	.word @ref59
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref72:
	.byte $f9,$85
@ref73:
	.byte $bf
@ref74:
	.byte $f9,$85
@ref75:
	.byte $f9,$85
@ref76:
	.byte $f9,$85
@ref77:
	.byte $f9,$85
@ref78:
	.byte $f9,$85
@ref79:
	.byte $f9,$85
@ref80:
	.byte $f9,$85
@ref81:
	.byte $f9,$85
@ref82:
	.byte $f9,$85
@ref83:
	.byte $f9,$85
@ref84:
	.byte $f9,$85
@ref85:
	.byte $f9,$85
@ref86:
	.byte $f9,$85
@ref87:
	.byte $f9,$85
@ref88:
	.byte $f9,$85
@ref89:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop
