;this file for FamiTone2 library generated by text2data tool

nq_nespeccy_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env4,@env0,@env0
	.byte $00
	.byte $f0 ;instrument $02
	.word @env2,@env17,@env0
	.byte $00
	.byte $f0 ;instrument $03
	.word @env3,@env17,@env0
	.byte $00
	.byte $f0 ;instrument $04
	.word @env2,@env18,@env0
	.byte $00
	.byte $f0 ;instrument $05
	.word @env3,@env18,@env0
	.byte $00
	.byte $f0 ;instrument $06
	.word @env2,@env19,@env0
	.byte $00
	.byte $f0 ;instrument $07
	.word @env3,@env19,@env0
	.byte $00
	.byte $f0 ;instrument $08
	.word @env2,@env20,@env0
	.byte $00
	.byte $f0 ;instrument $09
	.word @env3,@env20,@env0
	.byte $00
	.byte $30 ;instrument $0a
	.word @env1,@env16,@env0
	.byte $00
	.byte $30 ;instrument $0b
	.word @env1,@env21,@env0
	.byte $00
	.byte $30 ;instrument $0c
	.word @env5,@env22,@env0
	.byte $00
	.byte $30 ;instrument $0d
	.word @env6,@env23,@env0
	.byte $00
	.byte $30 ;instrument $0e
	.word @env7,@env24,@env0
	.byte $00
	.byte $30 ;instrument $0f
	.word @env8,@env25,@env0
	.byte $00
	.byte $30 ;instrument $10
	.word @env9,@env26,@env0
	.byte $00
	.byte $30 ;instrument $11
	.word @env10,@env27,@env0
	.byte $00
	.byte $30 ;instrument $12
	.word @env11,@env28,@env0
	.byte $00
	.byte $30 ;instrument $13
	.word @env12,@env29,@env0
	.byte $00
	.byte $30 ;instrument $14
	.word @env13,@env30,@env0
	.byte $00
	.byte $b0 ;instrument $15
	.word @env14,@env31,@env0
	.byte $00
	.byte $b0 ;instrument $16
	.word @env15,@env0,@env35
	.byte $00
	.byte $b0 ;instrument $17
	.word @env14,@env32,@env0
	.byte $00
	.byte $b0 ;instrument $18
	.word @env1,@env33,@env0
	.byte $00
	.byte $b0 ;instrument $19
	.word @env15,@env33,@env0
	.byte $00
	.byte $f0 ;instrument $1a
	.word @env3,@env34,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$00,$00
@env2:
	.byte $c0,$c1,$c1,$c2,$c2,$c3,$c3,$c4,$c4,$c5,$02,$c6,$c6,$c7,$c7,$c8
	.byte $c8,$c9,$c9,$ca,$ca,$cb,$cb,$00,$16
@env3:
	.byte $cd,$02,$cc,$03,$cb,$02,$ca,$03,$c9,$03,$c8,$02,$c7,$03,$c6,$03
	.byte $c5,$02,$c4,$03,$c3,$02,$c2,$03,$c1,$03,$c0,$00,$1a
@env4:
	.byte $c5,$00,$00
@env5:
	.byte $c9,$c5,$c3,$c0,$00,$03
@env6:
	.byte $c0,$c1,$c2,$c2,$c3,$c3,$c4,$c5,$c5,$c6,$c7,$c7,$c8,$c8,$c9,$ca
	.byte $ca,$cb,$cc,$cc,$cd,$cd,$ce,$cf,$cd,$cb,$c9,$c7,$c5,$c3,$c2,$c0
	.byte $00,$1f
@env7:
	.byte $cf,$04,$c0,$00,$02
@env8:
	.byte $c9,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$03,$c2,$03,$c1,$04
	.byte $c0,$00,$10
@env9:
	.byte $cf,$09,$c0,$00,$02
@env10:
	.byte $cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00
	.byte $0e
@env11:
	.byte $cf,$cf,$c0,$cf,$cf,$c0,$cf,$cf,$c0,$cf,$04,$c0,$00,$0b
@env12:
	.byte $cf,$cb,$c5,$cf,$cb,$c5,$cf,$cb,$c5,$cf,$cb,$c5,$c4,$c3,$c2,$c1
	.byte $00,$0f
@env13:
	.byte $c9,$c5,$c3,$03,$c2,$07,$c1,$08,$c0,$00,$08
@env14:
	.byte $cd,$ce,$00,$01
@env15:
	.byte $c4,$04,$c4,$00,$00
@env16:
	.byte $c0,$02,$bf,$04,$be,$03,$bd,$04,$bc,$03,$bb,$04,$ba,$03,$b9,$03
	.byte $b8,$04,$b7,$03,$b6,$b6,$b5,$b5,$b4,$00,$18
@env17:
	.byte $c0,$c0,$c3,$c3,$c7,$c7,$ca,$cc,$cf,$00,$00
@env18:
	.byte $c0,$c0,$c2,$c2,$c7,$c7,$ca,$cc,$ce,$00,$00
@env19:
	.byte $c0,$c0,$c2,$c2,$c5,$c5,$ca,$cc,$ce,$00,$00
@env20:
	.byte $c0,$c0,$c4,$c4,$c7,$c7,$c9,$cc,$c4,$00,$00
@env21:
	.byte $ab,$ac,$ad,$ad,$ae,$ae,$af,$02,$b0,$b0,$b1,$02,$b2,$b2,$b3,$b3
	.byte $b4,$02,$b5,$b5,$b6,$02,$b7,$b7,$b8,$b8,$b9,$02,$ba,$ba,$bb,$02
	.byte $bc,$bc,$bd,$bd,$be,$02,$bf,$bf,$c0,$00,$28
@env22:
	.byte $bc,$be,$bf,$c0,$00,$03
@env23:
	.byte $b5,$b5,$b6,$b6,$b7,$b7,$b8,$02,$b9,$b9,$ba,$ba,$bb,$bb,$bc,$bc
	.byte $bd,$bd,$be,$be,$bf,$bf,$c0,$00,$16
@env24:
	.byte $bc,$b8,$ae,$a9,$00,$03
@env25:
	.byte $c0,$09,$bf,$0b,$be,$0a,$bd,$0a,$bc,$02,$bc,$00,$0a
@env26:
	.byte $c0,$be,$bc,$ba,$b8,$b6,$b4,$b2,$b0,$00,$08
@env27:
	.byte $c6,$c3,$c0,$bd,$c0,$bd,$c0,$bd,$c0,$bd,$00,$09
@env28:
	.byte $c0,$bb,$b6,$c0,$bb,$b6,$c0,$bb,$b6,$c0,$bb,$b6,$b4,$b2,$b0,$00
	.byte $0e
@env29:
	.byte $c6,$c3,$c0,$c6,$c3,$c0,$c6,$c3,$c0,$bd,$c0,$bd,$c0,$bd,$c0,$bd
	.byte $00,$0f
@env30:
	.byte $bc,$be,$00,$01
@env31:
	.byte $be,$ca,$bf,$c0,$00,$03
@env32:
	.byte $c0,$cc,$c0,$c0,$00,$03
@env33:
	.byte $c0,$c1,$c0,$00,$02
@env34:
	.byte $c0,$c0,$c5,$c5,$c8,$c8,$ca,$cc,$c5,$00,$00
@env35:
	.byte $c1,$02,$c0,$c0,$c0,$00,$00


@song0ch0:
	.byte $fb,$03
@song0ch0loop:
@ref0:
	.byte $fb,$0c,$80,$5a,$9d,$fb,$03,$82,$63,$00,$85,$fb,$08,$93,$fb,$0c
	.byte $80,$5a,$9d,$fb,$03,$82,$63,$00,$99
@ref1:
	.byte $80,$5a,$dd,$82,$63,$00,$99
	.byte $ff,$05
	.word @ref1
@ref3:
	.byte $80,$58,$dd,$82,$5f,$00,$99
	.byte $ff,$05
	.word @ref3
@ref5:
	.byte $80,$5a,$85,$43,$82,$5b,$80,$4d,$82,$43,$80,$5b,$82,$4d,$80,$43
	.byte $82,$5b,$80,$4d,$82,$43,$80,$5b,$82,$4d,$80,$43,$82,$5b,$80,$3d
	.byte $82,$43,$80,$43,$82,$3d,$80,$4d,$82,$43,$80,$43,$82,$4d,$80,$43
	.byte $82,$43,$80,$4d,$82,$43,$80,$55,$82,$4d,$80,$4d,$82,$54,$81
@ref6:
	.byte $80,$5b,$82,$4d,$80,$41,$82,$5b,$80,$47,$82,$41,$80,$5b,$82,$47
	.byte $80,$41,$82,$5b,$80,$47,$82,$41,$80,$59,$82,$47,$80,$41,$82,$59
	.byte $80,$47,$82,$41,$80,$5f,$82,$47,$80,$41,$82,$5f,$80,$47,$82,$41
	.byte $80,$59,$82,$47,$80,$41,$82,$59,$80,$51,$82,$41,$80,$47,$82,$50
	.byte $81
@ref7:
	.byte $80,$59,$82,$47,$80,$41,$82,$59,$80,$51,$82,$41,$80,$5f,$82,$51
	.byte $80,$41,$82,$5f,$80,$51,$82,$41,$80,$59,$82,$51,$80,$41,$82,$59
	.byte $80,$51,$82,$41,$80,$5f,$82,$51,$80,$41,$82,$5f,$80,$51,$82,$41
	.byte $80,$59,$82,$51,$80,$47,$82,$59,$80,$55,$82,$47,$80,$51,$82,$54
	.byte $81
@ref8:
	.byte $80,$59,$82,$51,$80,$41,$82,$59,$80,$51,$82,$41,$80,$5f,$82,$51
	.byte $80,$41,$82,$5f,$80,$51,$82,$41,$80,$59,$82,$51,$80,$41,$82,$59
	.byte $80,$51,$82,$41,$80,$5f,$82,$51,$80,$41,$82,$5f,$80,$51,$82,$41
	.byte $80,$59,$82,$51,$01,$59,$00,$8d
@ref9:
	.byte $aa,$64,$8d,$ac,$64,$85,$ae,$62,$89,$ac,$65,$aa,$5a,$85,$ac,$63
	.byte $80,$59,$ac,$5a,$85,$aa,$5a,$8d,$ac,$5a,$85,$ae,$58,$89,$ac,$5a
	.byte $89,$aa,$50,$85,$ac,$58,$85
@ref10:
	.byte $aa,$5e,$8d,$82,$58,$85,$ae,$62,$89,$82,$5f,$aa,$5a,$85,$82,$63
	.byte $80,$59,$82,$5a,$85,$aa,$5e,$8d,$ac,$58,$85,$ae,$5a,$89,$82,$5f
	.byte $80,$4d,$ae,$51,$80,$55,$4d,$ae,$55,$80,$58,$81
@ref11:
	.byte $aa,$5a,$89,$82,$55,$ae,$58,$85,$82,$5a,$85,$80,$54,$85,$58,$85
	.byte $82,$54,$85,$aa,$5a,$89,$82,$59,$ae,$5e,$85,$82,$5b,$80,$5a,$85
	.byte $82,$5f,$aa,$58,$85,$80,$55,$ae,$51,$80,$47,$41,$ae,$47,$80,$50
	.byte $81
@ref12:
	.byte $aa,$58,$89,$ae,$55,$82,$58,$85,$ae,$5e,$89,$59,$82,$5e,$85,$aa
	.byte $62,$8d,$ae,$69,$80,$5f,$63,$ae,$59,$80,$5e,$54,$58,$50,$54,$4a
	.byte $50,$46,$4a,$50,$54,$50,$54,$58,$54,$58,$5e,$58,$5e,$60,$62,$85
@ref13:
	.byte $82,$62,$85,$80,$58,$5a,$83,$b0,$58,$85,$5a,$85,$82,$58,$85,$b0
	.byte $54,$85,$82,$5a,$85,$b0,$5a,$85,$82,$54,$85,$80,$62,$64,$83,$b0
	.byte $5a,$85,$58,$85,$82,$5a,$85,$80,$60,$62,$83,$b0,$58,$85,$54,$85
@ref14:
	.byte $82,$58,$85,$80,$54,$58,$83,$b0,$54,$85,$58,$85,$82,$54,$85,$b0
	.byte $5e,$85,$82,$58,$85,$b0,$62,$85,$82,$5e,$85,$80,$66,$68,$83,$b0
	.byte $62,$85,$58,$85,$80,$60,$62,$83,$b0,$58,$85,$54,$85,$58,$85
@ref15:
	.byte $82,$54,$85,$80,$56,$58,$83,$b0,$54,$85,$58,$85,$50,$85,$46,$85
	.byte $50,$85,$80,$5c,$5e,$83,$82,$50,$85,$b0,$58,$85,$82,$5e,$85,$b0
	.byte $62,$85,$82,$58,$85,$80,$56,$58,$83,$b0,$54,$85,$58,$85
@ref16:
	.byte $82,$54,$85,$80,$5c,$5e,$87,$b0,$4a,$85,$82,$5f,$80,$4e,$50,$83
	.byte $5c,$5e,$87,$b0,$4a,$85,$82,$5f,$80,$52,$54,$83,$b0,$5e,$85,$80
	.byte $4b,$b0,$51,$80,$55,$4b,$51,$b0,$59,$80,$4b,$b0,$59,$80,$60,$62
	.byte $87,$82,$58,$81
@ref17:
	.byte $62,$85,$b0,$65,$82,$63,$b0,$65,$01,$63,$b2,$65,$80,$63,$b2,$63
	.byte $b0,$5b,$82,$63,$80,$58,$5a,$87,$82,$5b,$b0,$5b,$01,$80,$5b,$01
	.byte $b0,$59,$82,$5b,$80,$59,$b2,$59,$80,$56,$58,$83,$b0,$51,$82,$59
	.byte $80,$4e,$50,$83,$4b,$b2,$50,$81
@ref18:
	.byte $83,$82,$4b,$b0,$63,$82,$4b,$80,$63,$01,$48,$4a,$83,$b0,$59,$82
	.byte $4b,$80,$59,$00,$85,$b2,$59,$80,$52,$54,$83,$b0,$59,$82,$55,$80
	.byte $59,$01,$4e,$50,$83,$b0,$63,$82,$51,$80,$60,$62,$83,$01,$82,$63
	.byte $80,$5c,$5e,$87,$b2,$62,$81
@ref19:
	.byte $82,$5e,$85,$b0,$5f,$01,$5f,$01,$80,$51,$b2,$5f,$b0,$59,$82,$51
	.byte $b0,$59,$82,$59,$01,$b2,$59,$80,$55,$01,$b0,$59,$82,$55,$b0,$59
	.byte $01,$80,$51,$b2,$59,$b0,$55,$82,$51,$80,$52,$54,$83,$01,$b2,$55
	.byte $80,$4e,$50,$83,$01,$82,$54,$81
@ref20:
	.byte $50,$85,$b0,$59,$01,$80,$59,$01,$55,$b2,$59,$80,$58,$82,$54,$80
	.byte $59,$01,$55,$82,$59,$80,$5e,$82,$54,$b0,$5f,$82,$55,$80,$59,$b2
	.byte $5f,$80,$62,$82,$58,$b0,$63,$80,$5c,$5e,$83,$68,$82,$5e,$b0,$69
	.byte $80,$60,$62,$83,$6c,$68,$62,$5e,$68,$62,$5e,$58,$b0,$62,$82,$5e
	.byte $80,$58,$82,$50
@ref21:
	.byte $00,$f9,$83
@ref22:
	.byte $00,$f9,$83
@ref23:
	.byte $00,$f9,$83
@ref24:
	.byte $00,$f9,$83
@ref25:
	.byte $80,$5a,$a5,$82,$5b,$50,$81
	.byte $ff,$19
	.word @ref9
	.byte $ff,$1b
	.word @ref10
	.byte $ff,$1f
	.word @ref11
	.byte $ff,$26
	.word @ref12
	.byte $ff,$23
	.word @ref13
	.byte $ff,$23
	.word @ref14
	.byte $ff,$23
	.word @ref15
	.byte $ff,$23
	.word @ref16
	.byte $ff,$23
	.word @ref17
	.byte $ff,$25
	.word @ref18
	.byte $ff,$23
	.word @ref19
	.byte $ff,$2c
	.word @ref20
@ref38:
	.byte $00,$f9,$83
@ref39:
	.byte $00,$f9,$83
@ref40:
	.byte $00,$f9,$83
@ref41:
	.byte $00,$f9,$83
	.byte $ff,$19
	.word @ref9
	.byte $ff,$1b
	.word @ref10
	.byte $ff,$1f
	.word @ref11
	.byte $ff,$26
	.word @ref12
	.byte $ff,$23
	.word @ref13
	.byte $ff,$23
	.word @ref14
	.byte $ff,$23
	.word @ref15
	.byte $ff,$23
	.word @ref16
@ref50:
	.byte $62,$85,$b0,$65,$82,$63,$b0,$65,$01,$63,$b2,$65,$80,$63,$b2,$63
	.byte $b0,$5b,$82,$63,$80,$58,$5a,$87,$82,$5b,$b0,$5b,$ac,$5a,$a5,$54
	.byte $91
@ref51:
	.byte $00,$ad,$80,$54,$00,$54,$00,$58,$5a,$83
@ref52:
	.byte $b0,$65,$5b,$b2,$65,$b0,$5a,$85,$80,$55,$b2,$5b,$82,$55,$b2,$5b
	.byte $b0,$5b,$55,$80,$51,$52,$54,$51,$b0,$4d,$82,$51,$b0,$4c,$00,$4d
	.byte $01,$50,$00,$51,$b2,$4d,$80,$54,$82,$50,$b0,$54,$00,$80,$5e,$82
	.byte $54,$b0,$5b,$82,$5f,$b0,$5f,$80,$58,$5a,$83,$b0,$55,$82,$5a,$81
@ref53:
	.byte $b0,$59,$63,$82,$59,$80,$5c,$5e,$83,$59,$b0,$51,$80,$59,$b0,$51
	.byte $59,$82,$51,$80,$54,$58,$83,$51,$b0,$4b,$80,$51,$b0,$4b,$80,$51
	.byte $4b,$59,$b0,$51,$80,$59,$b0,$51,$80,$59,$5e,$58,$62,$5e,$68,$62
	.byte $6c,$68,$62,$68,$62,$5e,$62,$5e,$58,$5e
@ref54:
	.byte $54,$58,$87,$82,$59,$b0,$54,$85,$82,$59,$80,$56,$58,$87,$b0,$51
	.byte $82,$59,$b0,$59,$82,$51,$b0,$63,$b2,$59,$80,$5c,$5e,$87,$b2,$63
	.byte $b0,$58,$85,$82,$5f,$80,$5c,$5e,$87,$b0,$59,$82,$5f,$80,$52,$54
	.byte $83,$b0,$59,$82,$54,$81
@ref55:
	.byte $80,$54,$58,$87,$82,$59,$b0,$54,$85,$82,$59,$80,$56,$58,$87,$b0
	.byte $51,$82,$59,$80,$48,$4a,$83,$b0,$55,$82,$4b,$80,$4e,$50,$87,$82
	.byte $55,$80,$52,$54,$87,$82,$51,$80,$56,$58,$83,$b0,$55,$80,$59,$5e
	.byte $58,$62,$5e,$82,$58,$50,$5e,$58
	.byte $ff,$23
	.word @ref17
	.byte $ff,$25
	.word @ref18
	.byte $ff,$23
	.word @ref19
	.byte $ff,$2c
	.word @ref20
@ref60:
	.byte $80,$52,$54,$87,$82,$55,$b0,$43,$4d,$51,$55,$4d,$b2,$51,$80,$5b
	.byte $b2,$55,$80,$56,$58,$83,$5b,$82,$59,$80,$52,$54,$87,$82,$5b,$b0
	.byte $43,$4d,$51,$55,$80,$3d,$43,$4d,$51,$b0,$35,$3d,$43,$4c,$81
@ref61:
	.byte $80,$52,$54,$87,$82,$55,$b0,$43,$4d,$51,$55,$b2,$4d,$51,$80,$5b
	.byte $82,$55,$80,$56,$58,$83,$5b,$82,$59,$80,$58,$5a,$87,$82,$5b,$b0
	.byte $43,$4d,$55,$5b,$80,$4d,$55,$5b,$65,$54,$42,$4c,$3c,$42,$34,$3c
	.byte $2a
@ref62:
	.byte $54,$58,$83,$82,$59,$b0,$4a,$85,$82,$59,$80,$4e,$50,$83,$82,$4b
	.byte $51,$b0,$4a,$85,$80,$4e,$50,$83,$b0,$4b,$82,$51,$b0,$40,$85,$82
	.byte $4b,$b0,$50,$85,$b2,$41,$80,$48,$4a,$8b,$82,$50,$85,$80,$44,$46
	.byte $87,$82,$4a,$81
@ref63:
	.byte $80,$54,$58,$83,$82,$47,$b0,$4a,$85,$82,$59,$80,$4e,$50,$83,$82
	.byte $4b,$51,$b0,$4a,$85,$80,$56,$58,$83,$b0,$4b,$82,$59,$80,$3e,$40
	.byte $83,$b0,$3d,$39,$80,$3a,$3c,$83,$b0,$39,$33,$80,$36,$38,$83,$33
	.byte $b0,$39,$80,$41,$b0,$47,$4b,$80,$50,$81
@ref64:
	.byte $82,$47,$4b,$80,$52,$54,$9b,$82,$52,$54,$83,$80,$43,$4d,$4e,$50
	.byte $55,$82,$4e,$50,$55,$80,$5a,$9d,$82,$63,$00,$91
@ref65:
	.byte $fb,$21,$00,$f9,$83
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref66:
	.byte $00,$f9,$83
@ref67:
	.byte $84,$3c,$dd,$86,$3c,$9d
@ref68:
	.byte $88,$3c,$dd,$8a,$3c,$9d
@ref69:
	.byte $8c,$3c,$dd,$8e,$3c,$9d
@ref70:
	.byte $90,$38,$dd,$92,$38,$9d
	.byte $ff,$04
	.word @ref67
	.byte $ff,$04
	.word @ref68
	.byte $ff,$04
	.word @ref69
	.byte $ff,$04
	.word @ref70
@ref75:
	.byte $86,$3c,$95,$3c,$a5,$3c,$95,$3c,$a5
@ref76:
	.byte $8a,$3c,$95,$3c,$a5,$3c,$95,$3c,$95,$3c,$8d
@ref77:
	.byte $8e,$3c,$95,$3c,$a5,$3c,$95,$3c,$a5
@ref78:
	.byte $92,$38,$95,$38,$a5,$38,$95,$38,$95,$38,$8d
	.byte $ff,$08
	.word @ref75
	.byte $ff,$0a
	.word @ref76
	.byte $ff,$08
	.word @ref77
	.byte $ff,$0a
	.word @ref78
	.byte $ff,$08
	.word @ref75
	.byte $ff,$0a
	.word @ref76
	.byte $ff,$08
	.word @ref77
	.byte $ff,$0a
	.word @ref78
@ref87:
	.byte $86,$3c,$95,$3c,$a5,$3c,$95,$3c,$95,$40,$8d
@ref88:
	.byte $3c,$95,$3c,$a5,$3c,$95,$3c,$95,$40,$8d
@ref89:
	.byte $92,$38,$95,$38,$a5,$38,$95,$38,$95,$8a,$3c,$8d
	.byte $ff,$0a
	.word @ref89
@ref91:
	.byte $00,$ad
	.byte $ff,$08
	.word @ref75
	.byte $ff,$0a
	.word @ref76
	.byte $ff,$08
	.word @ref77
	.byte $ff,$0a
	.word @ref78
	.byte $ff,$08
	.word @ref75
	.byte $ff,$0a
	.word @ref76
	.byte $ff,$08
	.word @ref77
	.byte $ff,$0a
	.word @ref78
	.byte $ff,$08
	.word @ref75
	.byte $ff,$0a
	.word @ref76
	.byte $ff,$08
	.word @ref77
	.byte $ff,$0a
	.word @ref78
	.byte $ff,$0a
	.word @ref87
	.byte $ff,$0a
	.word @ref88
	.byte $ff,$0a
	.word @ref89
	.byte $ff,$0a
	.word @ref89
	.byte $ff,$08
	.word @ref75
	.byte $ff,$0a
	.word @ref76
	.byte $ff,$08
	.word @ref77
	.byte $ff,$0a
	.word @ref78
	.byte $ff,$08
	.word @ref75
	.byte $ff,$0a
	.word @ref76
	.byte $ff,$08
	.word @ref77
	.byte $ff,$0a
	.word @ref78
@ref116:
	.byte $86,$3c,$95,$3c,$a5,$3d,$80,$3c,$b9
@ref117:
	.byte $3c,$9d,$42,$8d,$82,$3c,$42,$46,$4c,$50,$54,$5a,$62
	.byte $ff,$08
	.word @ref75
	.byte $ff,$0a
	.word @ref76
	.byte $ff,$08
	.word @ref77
@ref121:
	.byte $92,$38,$95,$38,$a5,$38,$95,$38,$95,$90,$38,$8d
	.byte $ff,$08
	.word @ref75
	.byte $ff,$0a
	.word @ref76
	.byte $ff,$08
	.word @ref77
	.byte $ff,$0a
	.word @ref78
@ref126:
	.byte $84,$3c,$8d,$86,$3c,$8d,$84,$3c,$89,$86,$3c,$89,$8a,$3c,$85,$84
	.byte $3c,$8d,$86,$3c,$8d,$84,$3c,$89,$86,$3c,$89,$40,$85
	.byte $ff,$14
	.word @ref126
@ref128:
	.byte $90,$38,$8d,$92,$38,$8d,$90,$38,$89,$92,$38,$89,$b4,$36,$85,$90
	.byte $38,$8d,$92,$38,$8d,$90,$38,$89,$92,$38,$89,$8a,$3c,$85
	.byte $ff,$14
	.word @ref128
@ref130:
	.byte $84,$3c,$85,$86,$3c,$9d,$82,$63,$00,$d1
@ref131:
	.byte $00,$f9,$83
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref132:
	.byte $00,$dd,$96,$34,$9d
@ref133:
	.byte $94,$34,$dd,$00,$9d
@ref134:
	.byte $80,$1a,$dd,$96,$20,$9d
@ref135:
	.byte $80,$20,$dd,$96,$16,$9d
@ref136:
	.byte $80,$16,$dd,$96,$34,$9d
@ref137:
	.byte $94,$34,$bd,$00,$85,$80,$1c,$85,$00,$8d,$1c,$85,$00,$85,$1c,$85
	.byte $00,$85
@ref138:
	.byte $1a,$bd,$94,$1a,$9d,$96,$20,$9d
@ref139:
	.byte $80,$20,$bd,$00,$85,$20,$85,$00,$8d,$20,$85,$00,$85,$20,$85,$00
	.byte $85
@ref140:
	.byte $16,$bd,$94,$16,$9d,$00,$9d
@ref141:
	.byte $9c,$41,$80,$1d,$01,$1d,$a0,$49,$80,$2b,$9c,$41,$80,$35,$9c,$41
	.byte $80,$35,$25,$2b,$a0,$49,$80,$2b,$21,$1d,$9c,$41,$80,$1d,$01,$1d
	.byte $a0,$49,$80,$2b,$9c,$41,$80,$35,$9c,$41,$80,$35,$25,$2b,$a0,$49
	.byte $80,$2b,$21,$a4,$48,$81
@ref142:
	.byte $9c,$41,$80,$1b,$33,$01,$a0,$49,$80,$25,$9c,$41,$80,$25,$9c,$41
	.byte $80,$2b,$25,$01,$a0,$49,$80,$2b,$25,$33,$9c,$41,$80,$1b,$33,$a4
	.byte $49,$a0,$49,$80,$25,$9c,$41,$80,$25,$a0,$49,$80,$2b,$25,$9c,$41
	.byte $a0,$49,$80,$2b,$9c,$41,$80,$32,$81
@ref143:
	.byte $9c,$41,$80,$29,$2f,$29,$a0,$49,$80,$39,$9c,$41,$80,$2f,$9c,$41
	.byte $80,$2f,$39,$41,$a0,$49,$80,$2f,$29,$01,$9c,$41,$80,$29,$9c,$41
	.byte $80,$29,$a0,$49,$80,$39,$9c,$41,$80,$2f,$9c,$41,$80,$2f,$29,$a4
	.byte $49,$a0,$49,$80,$39,$2f,$a0,$48,$81
@ref144:
	.byte $9c,$41,$80,$1b,$33,$01,$a0,$49,$80,$33,$9c,$41,$80,$25,$9c,$41
	.byte $80,$25,$33,$01,$a0,$49,$80,$25,$21,$29,$9c,$41,$80,$1b,$33,$9c
	.byte $41,$a0,$49,$80,$33,$9c,$41,$80,$25,$a0,$48,$85,$80,$21,$29,$a0
	.byte $49,$80,$25,$21,$a4,$48,$81
	.byte $ff,$21
	.word @ref141
	.byte $ff,$21
	.word @ref142
	.byte $ff,$21
	.word @ref143
	.byte $ff,$21
	.word @ref144
	.byte $ff,$21
	.word @ref141
	.byte $ff,$21
	.word @ref142
	.byte $ff,$21
	.word @ref143
	.byte $ff,$21
	.word @ref144
@ref153:
	.byte $9c,$41,$80,$1d,$01,$1c,$85,$2b,$9c,$41,$80,$35,$a0,$49,$80,$35
	.byte $25,$2b,$01,$2b,$21,$1d,$9c,$41,$80,$1d,$01,$1d,$01,$2b,$9c,$41
	.byte $80,$35,$a0,$49,$80,$35,$25,$2b,$01,$2b,$21,$a4,$48,$81
	.byte $ff,$21
	.word @ref153
@ref155:
	.byte $9c,$41,$80,$1b,$33,$00,$85,$33,$9c,$41,$80,$25,$a0,$49,$80,$25
	.byte $33,$00,$85,$25,$21,$29,$9c,$41,$80,$1b,$33,$9c,$40,$85,$80,$33
	.byte $9c,$41,$80,$25,$a0,$48,$85,$80,$21,$28,$85,$25,$21,$a4,$48,$81
@ref156:
	.byte $9c,$41,$80,$1b,$33,$00,$85,$33,$9c,$41,$80,$25,$a0,$49,$80,$25
	.byte $33,$00,$85,$25,$21,$29,$9c,$41,$80,$1b,$33,$9c,$41,$a0,$49,$80
	.byte $33,$9c,$41,$80,$25,$a0,$48,$85,$80,$21,$29,$a0,$49,$80,$25,$21
	.byte $a4,$48,$81
@ref157:
	.byte $00,$ad
	.byte $ff,$21
	.word @ref141
	.byte $ff,$21
	.word @ref142
	.byte $ff,$21
	.word @ref143
	.byte $ff,$21
	.word @ref144
	.byte $ff,$21
	.word @ref141
	.byte $ff,$21
	.word @ref142
	.byte $ff,$21
	.word @ref143
	.byte $ff,$21
	.word @ref144
	.byte $ff,$21
	.word @ref141
	.byte $ff,$21
	.word @ref142
	.byte $ff,$21
	.word @ref143
	.byte $ff,$21
	.word @ref144
	.byte $ff,$21
	.word @ref141
	.byte $ff,$21
	.word @ref141
	.byte $ff,$21
	.word @ref144
	.byte $ff,$21
	.word @ref144
	.byte $ff,$21
	.word @ref141
	.byte $ff,$21
	.word @ref142
	.byte $ff,$21
	.word @ref143
	.byte $ff,$21
	.word @ref144
	.byte $ff,$21
	.word @ref141
	.byte $ff,$21
	.word @ref142
	.byte $ff,$21
	.word @ref143
	.byte $ff,$21
	.word @ref144
@ref182:
	.byte $9c,$41,$80,$1d,$01,$1d,$a0,$49,$80,$2b,$9c,$41,$80,$35,$9c,$41
	.byte $80,$35,$25,$2b,$a0,$49,$80,$2b,$21,$1d,$9c,$41,$80,$4c,$a5,$4a
	.byte $91
@ref183:
	.byte $48,$8d,$24,$8d,$96,$2a,$9d
	.byte $ff,$21
	.word @ref141
	.byte $ff,$21
	.word @ref142
	.byte $ff,$21
	.word @ref143
@ref187:
	.byte $9c,$41,$80,$1b,$33,$01,$a0,$49,$80,$33,$9c,$41,$80,$25,$9c,$41
	.byte $80,$25,$33,$01,$a0,$49,$80,$25,$21,$29,$9c,$41,$80,$1b,$33,$9c
	.byte $41,$a0,$49,$80,$33,$9c,$41,$80,$25,$9c,$40,$85,$a0,$49,$96,$2a
	.byte $91
	.byte $ff,$21
	.word @ref141
	.byte $ff,$21
	.word @ref142
	.byte $ff,$21
	.word @ref143
	.byte $ff,$21
	.word @ref144
	.byte $ff,$21
	.word @ref141
	.byte $ff,$21
	.word @ref141
	.byte $ff,$21
	.word @ref144
@ref195:
	.byte $9c,$41,$80,$1b,$33,$01,$a0,$49,$80,$33,$9c,$41,$80,$25,$9c,$41
	.byte $80,$25,$33,$01,$a0,$49,$80,$25,$21,$29,$9c,$41,$80,$1b,$33,$9c
	.byte $41,$41,$80,$33,$9c,$41,$80,$25,$9c,$40,$85,$a0,$49,$80,$25,$21
	.byte $a4,$49,$a0,$49,$80,$24,$81
@ref196:
	.byte $9c,$41,$80,$1d,$01,$1d,$9c,$41,$80,$1d,$00,$e5
@ref197:
	.byte $00,$f9,$83
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref198:
	.byte $00,$9d,$80,$14,$0f,$20,$00,$b5,$14,$0f,$20,$00,$95
@ref199:
	.byte $02,$04,$06,$08,$0a,$0a,$0c,$0c,$0e,$0e,$10,$10,$12,$12,$14,$14
	.byte $16,$16,$18,$18,$1a,$1a,$1c,$1c,$1e,$1e,$00,$a9,$14,$0f,$20,$00
	.byte $95
@ref200:
	.byte $df,$14,$0f,$20,$00,$95
	.byte $ff,$06
	.word @ref200
	.byte $ff,$06
	.word @ref200
@ref203:
	.byte $02,$04,$06,$08,$0a,$0a,$0c,$0c,$0e,$0e,$10,$10,$12,$12,$14,$14
	.byte $16,$16,$18,$18,$1a,$1a,$1c,$1c,$1e,$1e,$01,$98,$02,$85,$1c,$85
	.byte $02,$95,$80,$14,$0f,$20,$00,$85,$98,$1c,$8d
@ref204:
	.byte $1c,$9d,$1c,$95,$02,$85,$1c,$85,$02,$95,$80,$14,$0f,$20,$98,$02
	.byte $8d,$02,$85
@ref205:
	.byte $1c,$9d,$1c,$95,$02,$85,$1c,$85,$02,$95,$80,$14,$0f,$20,$00,$85
	.byte $98,$02,$8d
@ref206:
	.byte $1c,$9d,$1c,$95,$02,$85,$1c,$8d,$20,$8d,$20,$85,$02,$85,$9a,$1e
	.byte $8d
@ref207:
	.byte $9e,$18,$85,$98,$1d,$21,$a2,$12,$85,$a8,$1c,$85,$98,$1d,$21,$03
	.byte $1d,$a2,$14,$85,$98,$1d,$21,$9e,$18,$85,$98,$1d,$21,$a2,$12,$85
	.byte $a8,$1c,$85,$98,$1d,$21,$03,$1d,$a2,$14,$85,$98,$1d,$a6,$12,$81
@ref208:
	.byte $9e,$18,$85,$98,$1d,$21,$a2,$12,$85,$a8,$1c,$85,$98,$1d,$21,$03
	.byte $1d,$a2,$14,$85,$98,$1d,$21,$9e,$18,$85,$98,$1d,$a6,$13,$a2,$12
	.byte $85,$a8,$1c,$85,$a2,$12,$85,$98,$03,$1d,$a2,$14,$85,$a8,$1d,$98
	.byte $20,$81
@ref209:
	.byte $9e,$18,$85,$98,$1d,$21,$a2,$12,$85,$a8,$1c,$85,$98,$1d,$21,$03
	.byte $1d,$a2,$14,$85,$98,$1d,$21,$9e,$18,$85,$a8,$1d,$98,$21,$a2,$12
	.byte $85,$a8,$1c,$85,$98,$1d,$21,$03,$a6,$13,$a2,$14,$85,$98,$1d,$a2
	.byte $12,$81
@ref210:
	.byte $9e,$18,$85,$98,$1d,$21,$a2,$12,$85,$a8,$1c,$85,$98,$1d,$21,$03
	.byte $1d,$a2,$14,$85,$98,$1d,$21,$9e,$18,$85,$98,$1d,$21,$a2,$12,$85
	.byte $a8,$1c,$85,$a2,$14,$85,$98,$03,$1d,$a2,$14,$85,$98,$1d,$a6,$12
	.byte $81
	.byte $ff,$21
	.word @ref207
	.byte $ff,$21
	.word @ref208
	.byte $ff,$21
	.word @ref209
	.byte $ff,$21
	.word @ref210
	.byte $ff,$21
	.word @ref207
	.byte $ff,$21
	.word @ref208
	.byte $ff,$21
	.word @ref209
	.byte $ff,$21
	.word @ref210
@ref219:
	.byte $9e,$18,$85,$98,$1d,$20,$89,$a8,$1c,$85,$a2,$12,$85,$98,$03,$1c
	.byte $89,$1d,$21,$9e,$18,$85,$98,$1d,$21,$00,$85,$a8,$1c,$85,$a2,$14
	.byte $85,$98,$03,$1c,$89,$1d,$a6,$12,$81
	.byte $ff,$1e
	.word @ref219
@ref221:
	.byte $9e,$18,$85,$98,$1d,$20,$89,$a8,$1c,$85,$a2,$14,$85,$98,$03,$1c
	.byte $89,$1d,$21,$9e,$18,$85,$98,$1d,$20,$89,$a8,$1c,$85,$a2,$14,$85
	.byte $98,$03,$1c,$89,$1d,$a6,$12,$81
@ref222:
	.byte $9e,$18,$85,$98,$1d,$20,$89,$a8,$1c,$85,$a2,$14,$85,$98,$03,$1c
	.byte $89,$1d,$21,$9e,$18,$85,$98,$1d,$21,$a2,$12,$85,$a8,$1c,$85,$a2
	.byte $14,$85,$98,$03,$1d,$a2,$14,$85,$98,$1d,$a6,$12,$81
@ref223:
	.byte $00,$9d,$9a,$1e,$8d
	.byte $ff,$21
	.word @ref207
	.byte $ff,$21
	.word @ref208
	.byte $ff,$21
	.word @ref209
	.byte $ff,$21
	.word @ref210
	.byte $ff,$21
	.word @ref207
	.byte $ff,$21
	.word @ref208
	.byte $ff,$21
	.word @ref209
	.byte $ff,$21
	.word @ref210
	.byte $ff,$21
	.word @ref207
	.byte $ff,$21
	.word @ref208
	.byte $ff,$21
	.word @ref209
	.byte $ff,$21
	.word @ref210
	.byte $ff,$21
	.word @ref207
	.byte $ff,$21
	.word @ref207
	.byte $ff,$21
	.word @ref210
	.byte $ff,$21
	.word @ref210
	.byte $ff,$21
	.word @ref207
	.byte $ff,$21
	.word @ref208
	.byte $ff,$21
	.word @ref209
	.byte $ff,$21
	.word @ref210
	.byte $ff,$21
	.word @ref207
	.byte $ff,$21
	.word @ref208
	.byte $ff,$21
	.word @ref209
	.byte $ff,$21
	.word @ref210
@ref248:
	.byte $9e,$18,$85,$98,$1d,$21,$a2,$12,$85,$a8,$1c,$85,$98,$1d,$21,$03
	.byte $1d,$a2,$14,$85,$98,$1d,$21,$9e,$19,$80,$1a,$a5,$16,$91
@ref249:
	.byte $12,$8d,$20,$8d,$02,$8d,$04,$06,$08,$0a,$9a,$1e,$85
	.byte $ff,$21
	.word @ref207
	.byte $ff,$21
	.word @ref208
	.byte $ff,$21
	.word @ref209
@ref253:
	.byte $9e,$18,$85,$98,$1d,$21,$a2,$12,$85,$a8,$1c,$85,$98,$1d,$21,$03
	.byte $1d,$a2,$14,$85,$98,$1d,$21,$9e,$18,$85,$98,$1d,$21,$a2,$12,$85
	.byte $a8,$1c,$85,$9e,$18,$85,$a2,$14,$85,$9a,$1e,$8d
	.byte $ff,$21
	.word @ref207
	.byte $ff,$21
	.word @ref208
	.byte $ff,$21
	.word @ref209
	.byte $ff,$21
	.word @ref210
	.byte $ff,$21
	.word @ref207
	.byte $ff,$21
	.word @ref207
	.byte $ff,$21
	.word @ref210
@ref261:
	.byte $9e,$18,$85,$98,$1d,$21,$a2,$12,$85,$a8,$1c,$85,$98,$1d,$21,$03
	.byte $1d,$a2,$14,$85,$98,$1d,$21,$9e,$18,$85,$98,$1d,$21,$9e,$18,$85
	.byte $98,$1d,$21,$9e,$18,$85,$a2,$14,$85,$98,$1d,$a6,$13,$a2,$14,$85
@ref262:
	.byte $9e,$18,$85,$98,$1d,$21,$9e,$18,$95,$80,$14,$0f,$20,$00,$b5,$14
	.byte $0f,$20,$00,$8d
@ref263:
	.byte $00,$f9,$83
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref264:
	.byte $f9,$85
@ref265:
	.byte $f9,$85
@ref266:
	.byte $f9,$85
@ref267:
	.byte $f9,$85
@ref268:
	.byte $f9,$85
@ref269:
	.byte $f9,$85
@ref270:
	.byte $f9,$85
@ref271:
	.byte $f9,$85
@ref272:
	.byte $f9,$85
@ref273:
	.byte $f9,$85
@ref274:
	.byte $f9,$85
@ref275:
	.byte $f9,$85
@ref276:
	.byte $f9,$85
@ref277:
	.byte $f9,$85
@ref278:
	.byte $f9,$85
@ref279:
	.byte $f9,$85
@ref280:
	.byte $f9,$85
@ref281:
	.byte $f9,$85
@ref282:
	.byte $f9,$85
@ref283:
	.byte $f9,$85
@ref284:
	.byte $f9,$85
@ref285:
	.byte $f9,$85
@ref286:
	.byte $f9,$85
@ref287:
	.byte $f9,$85
@ref288:
	.byte $f9,$85
@ref289:
	.byte $af
@ref290:
	.byte $f9,$85
@ref291:
	.byte $f9,$85
@ref292:
	.byte $f9,$85
@ref293:
	.byte $f9,$85
@ref294:
	.byte $f9,$85
@ref295:
	.byte $f9,$85
@ref296:
	.byte $f9,$85
@ref297:
	.byte $f9,$85
@ref298:
	.byte $f9,$85
@ref299:
	.byte $f9,$85
@ref300:
	.byte $f9,$85
@ref301:
	.byte $f9,$85
@ref302:
	.byte $f9,$85
@ref303:
	.byte $f9,$85
@ref304:
	.byte $f9,$85
@ref305:
	.byte $f9,$85
@ref306:
	.byte $f9,$85
@ref307:
	.byte $f9,$85
@ref308:
	.byte $f9,$85
@ref309:
	.byte $f9,$85
@ref310:
	.byte $f9,$85
@ref311:
	.byte $f9,$85
@ref312:
	.byte $f9,$85
@ref313:
	.byte $f9,$85
@ref314:
	.byte $f9,$85
@ref315:
	.byte $bf
@ref316:
	.byte $f9,$85
@ref317:
	.byte $f9,$85
@ref318:
	.byte $f9,$85
@ref319:
	.byte $f9,$85
@ref320:
	.byte $f9,$85
@ref321:
	.byte $f9,$85
@ref322:
	.byte $f9,$85
@ref323:
	.byte $f9,$85
@ref324:
	.byte $f9,$85
@ref325:
	.byte $f9,$85
@ref326:
	.byte $f9,$85
@ref327:
	.byte $f9,$85
@ref328:
	.byte $f9,$85
@ref329:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop
